/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [278.42KB] > C:\Users\Sushant Kumar\Downloads\Boy-avt\boy_warrior\scene-transformed.glb [212.34KB] (24%)
Author: botupo (https://sketchfab.com/botupo3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boy-warrior-66707b5e61444da3ad8f1502530db9f8
Title: Boy warrior
*/
"use client";
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Sword} position={[0.176, 0.206, -0.078]} rotation={[3.066, 0.633, 0.397]} scale={0.653} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_0} skeleton={nodes.Object_10.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
